- name: include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: filebeat

- name: include OS-specific tasks
  include: "{{ ansible_os_family }}.yml"
  become: yes
  tags: filebeat
  
- name: copy pipeline file
  template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml
    mode: 0644
  notify:
    - restart filebeat
  become: yes
  tags: filebeat

- name: enable filebeat service
  service:
    name: filebeat
    state: started
    enabled: yes
  become: yes
  tags: filebeat